version: "2"
services:
  api:
    container_name: api
    build: ./api
    command: ["./wait-for-it.sh", "0.0.0.0:5432", "--", "npm", "start"]
    depends_on:
      - database
    links:
      - database
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - REDIS_HOST=redis
    volumes:
      - ./api:/app
      - app/node_modules
    restart: on-failure

  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  redis:
    image: redis